site_name: FIP doc
site_url: https://vvinceb.github.io/docs/
nav:
  - Home: index.md
  - Data management: dataMgmt.md
  - Feeder: feeder.md
  - Consumer: consumer.md
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: indigo
        accent: cyan

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: indigo
        accent: cyan


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

#extra:
  # generator: false
